sudo: required
language: java
jdk: oraclejdk8
install: true
env:
  local:
    maven:
    - repository=$HOME/.m2
before_install:

cache:
  directories:
  - "$HOME/.m2"

script:
- mvn clean install

deploy:
- provider: script
  skip_cleanup: true
  script: mvn deploy -Dmaven.test.skip=true --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: mvn release:clean release:prepare -Prelease-sign-artifacts -DautoVersionSubm --settings travis-maven-settings.xml -Dsettings.security=travis-maven-settings-security.xml -B
  on:
    branch: master
    tags: true
